### ISSUE TITLE
Generate HTML with team roster

### ISSUE THREAD

**Issue by tracybrtn** [tracybrtn/team-profile-generator#1]
# Description

## User Story Prompts

WHEN I am prompted for my team members and their information
-	THEN an HTML file is generated that displays a nicely formatted team roster based on user input
WHEN I click on an email address in the HTML
-	THEN my default email program opens and populates the TO field of the email with the address
WHEN I click on the GitHub username
-	THEN that GitHub profile opens in a new tab

## Tasks
- [x] Generate HTML
- [x] Give functionality to HTML and HTML links (email and github)
- [x] Add style sheet
- [x] Create src and dist directories
